### ISSUE TITLE
Attribute name and qualified name must be identical

### ISSUE THREAD

**Issue by NoahMilam** [hydro0/unity-fabric-multidex-issue#1]
I am trying to use you fabric fix and am have some issues. the I add android:name="io.fabric.unity.android.MultiDexFabricApplication"  to the Assets/Plugins/Android AndroidMaifest.xml it gives me the error XmlException: Attribute name and qualified name must be identical. file:///Users/edgeworks/Documents/UnityWorkSpace/TerraGenesis-Unity/Assets/Plugins/Android/AndroidManifest.xml Line 15, position 282.

application android:theme="@style/UnityThemeSelector" android:icon="@drawable/app_icon" android:label="@string/app_name" android:name="io.fabric.unity.android.MultiDexFabricApplication"  android:name="io.fabric.unity.android.FabricApplication" android:resizeableActivity="false"

any thoughts on what I am doing wrong?

**Comment by hydro0** [comment]
Could you please share your `AndroidManifest.xml` source code ?

**Comment by hydro0** [comment]
If your `<application>` tag already has `android:name` attribute - you have to remove that one and leave only `android:name="io.fabric.unity.android.MultiDexFabricApplication"`.

**Comment by NoahMilam** [comment]
I did that and  go this error in the logcat

03-16 16:55:08.942 7070-7102/com.alexanderwinn.TerraGenesis E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetStringi:3762 GL error 0x501

03-16 16:55:12.172 1594-1836/system_process A/ProcessStats: ProcessState dead: name=com.android.systemui pkg=com.android.keyguard uid=10007 common.name=com.android.systemui
                                                            android.util.Log$TerribleFailure: ProcessState dead: name=com.android.systemui pkg=com.android.keyguard uid=10007 common.name=com.android.systemui
                                                                at android.util.Log.wtf(Log.java:290)
                                                                at android.util.Slog.wtfStack(Slog.java:86)
                                                                at com.android.internal.app.ProcessStats$ProcessState.ensureNotDead(ProcessStats.java:2495)
                                                                at com.android.internal.app.ProcessStats$ProcessState.setState(ProcessStats.java:2593)
                                                                at com.android.internal.app.ProcessStats$ProcessState.setState(ProcessStats.java:2578)
                                                                at com.android.server.am.ActivityManagerService.setProcessTrackerState(ActivityManagerService.java:15348)
                                                                at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:15631)
                                                                at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3754)
                                                                at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1026)
                                                                at android.os.BinderProxy.sendDeathNotice(Binder.java:493)
                                                                at dalvik.system.NativeStart.run(Native Method)
03-16 16:55:12.362 7070-7102/com.alexanderwinn.TerraGenesis E/eglCodecCommon: glUtilsParamSize: unknow param 0x0000912f
and here is my androidManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" android:installLocation="preferExternal" android:theme="@android:style/Theme.NoTitleBar">
  <!-- Helpshift required minSdkVersion of 16 & Google featuring requires Android 6 (25) -->
  <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="27" />
  <!-- BEGIN: INSERT DESIRED PERMISSION HERE, RUNTIME or INSTALL-TIME -->
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="com.android.vending.BILLING" />
  <!-- END: INSERT DESIRED PERMISSION HERE, RUNTIME or INSTALL-TIME -->
  <!-- Permission required by Omniata Android plugin -->
  <permission android:name="com.alexanderwinn.TerraGenesis.permission.C2D_MESSAGE" android:protectionLevel="signature" />
  <!-- Permission required by Omniata Android SDK for Push -->
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <supports-screens android:smallScreens="false" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@style/UnityThemeSelector" android:icon="@drawable/app_icon" android:label="@string/app_name" android:name="io.fabric.unity.android.FabricApplication" android:resizeableActivity="false">
    <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />
    <activity android:name="com.tiltingpoint.unitytools.TiltingPointUnityActivity" android:label="@string/app_name" android:launchMode="singleTask" android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>
      <!-- BEGIN: REMOVE OR CUSTOMIZE FOR BASIC APP-LAUNCH DEEP-LINKING -->
      <intent-filter android:label="TiltingPointDeeplinkIntent">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="tiltingpoint" android:host="com.alexanderwinn.TerraGenesis" />
      </intent-filter>
      <!-- END: REMOVE OR CUSTOMIZE FOR BASIC APP-LAUNCH DEEP-LINKING -->
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
      <meta-data android:name="android.app.lib_name" android:value="unity" />
    </activity>
    <receiver android:name="com.tiltingpoint.unitytools.TpLocalNotifReceiver" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="com.alexanderwinn.TerraGenesis" />
      </intent-filter>
    </receiver>
    <receiver android:name="com.adjust.sdk.AdjustReferrerReceiver" android:exported="true">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
    </receiver>
    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
    <!-- Supersonic -->
    <activity android:name="com.supersonicads.sdk.controller.ControllerActivity" android:configChanges="orientation|screenSize" android:hardwareAccelerated="true" />
    <activity android:name="com.supersonicads.sdk.controller.InterstitialActivity" android:configChanges="orientation|screenSize" android:hardwareAccelerated="true" android:theme="@android:style/Theme.Translucent" />
    <activity android:name="com.supersonicads.sdk.controller.OpenUrlActivity" android:configChanges="orientation|screenSize" android:hardwareAccelerated="true" />
    <activity android:name="com.unity3d.plugin.downloader.UnityDownloaderActivity" />
    <service android:name="com.unity3d.plugin.downloader.UnityDownloaderService" />
    <receiver android:name="com.unity3d.plugin.downloader.UnityAlarmReceiver" />
  </application>
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <uses-permission android:name="com.android.vending.CHECK_LICENSE" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
</manifest>
```

**Comment by hydro0** [comment]
You have to replace `android:name="io.fabric.unity.android.FabricApplication"` with `android:name="io.fabric.unity.android.MultiDexFabricApplication"`.
