### ISSUE TITLE
Unable to instantiate application io.fabric.unity.android.MultiDexFabricApplication

### ISSUE THREAD

**Issue by waynehsiao** [hydro0/unity-fabric-multidex-issue#2]
Hi, I've follow the intruction in README.md file.
But when I install my apk it will crash suddenly.
And following is the error log:
java.lang.RuntimeException: Unable to instantiate application io.fabric.unity.android.MultiDexFabricApplication: java.lang.ClassNotFoundException: Didn't find class "io.fabric.unity.android.MultiDexFabricApplication" on path: DexPathList[[zip file "/data/app/com.lifiTech.lifi-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lifiTech.lifi-1/lib/x86, /vendor/lib, /system/lib]]

Do I missing something?
Thanks

**Comment by hydro0** [comment]
Hey,

So you put that jar in the `Assets/Plugins/Android`?
If yes, then could you share the version of Unity and if it would be possible - apk file itself?

**Comment by waynehsiao** [comment]
I'm using Unity 2017.2.0.f3
I found that the issue was occur when I using android 5.0 device.
But it works in Android 6.0 and above.
Is there any different?

Thanks for ur help!

**Comment by hydro0** [comment]
Hmm, I have one solution on my mind, but could you please send me apk file? If it is restricted, could you decompile it then(using Android Studio would be the easiest way) and look in `classes.dex`, `classes2.dex` is there a class `io.fabric.unity.android.MultiDexFabricApplication` in any of them? If yes, and it is in `classes2.dex`, then I'll provide you a solution and explanation, if not - most likely you have some misconfigurations, I will try to guide you on how to deal with that.

**Comment by waynehsiao** [comment]
Hi

I've send my apk link to ur gmail.
Please let me know if u need additinal information about this issue.
Thank u!
